-- Fix relationships to allow joining with profiles
-- We want to reference public.profiles instead of auth.users for easier frontend joins

-- Drop old constraints (referencing auth.users)
-- Note: 'reviews_user_id_fkey' is the default name generated by Postgres if not specified.
-- If the previous creation script was run, these should exist.

ALTER TABLE public.reviews
DROP CONSTRAINT IF EXISTS reviews_user_id_fkey;

ALTER TABLE public.product_questions
DROP CONSTRAINT IF EXISTS product_questions_user_id_fkey;

ALTER TABLE public.product_answers
DROP CONSTRAINT IF EXISTS product_answers_user_id_fkey;

-- Add new constraints (referencing public.profiles)
ALTER TABLE public.reviews
ADD CONSTRAINT reviews_user_id_fkey
FOREIGN KEY (user_id) REFERENCES public.profiles(id)
ON DELETE CASCADE;

ALTER TABLE public.product_questions
ADD CONSTRAINT product_questions_user_id_fkey
FOREIGN KEY (user_id) REFERENCES public.profiles(id)
ON DELETE CASCADE;

ALTER TABLE public.product_answers
ADD CONSTRAINT product_answers_user_id_fkey
FOREIGN KEY (user_id) REFERENCES public.profiles(id)
ON DELETE CASCADE;
